language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install coveralls --use-mirrors
# command to run tests
script: nosetests -w dsptestbed/test/ --all-modules --with-coverage --cover-erase --cover-package=dsptestbed
after_success:
  - coveralls