language: python
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install coveralls --use-mirrors
# command to run tests
script: nosetests -w dsptestbed/test/ --all-modules --with-coverage --cover-erase --cover-package=dsptestbed
after_success:
  - coveralls